version: '3'
services:
  smf:
    container_name: smf
    build: .
    image: smf
    ports:
      - "8086:80"
    volumes:
    - ./database:/var/lib/mysql
    - ./smf:/var/www/html
    networks:
      - proxy
    env_file:
      - .env

networks:
  proxy:
    external: true
