version: '3'
services:
  smf:
    container_name: smf
    build: .
    image: smf
    ports:
      - "8086:80"
    networks:
      - proxy
    env_file:
      - .env

networks:
  proxy:
    external: true
